- name: Check ssh connectivity
  ping:

#- name: Debug 
#  debug: 
#    msg: "hostvars: {{ hostvars | to_nice_json}}"
- name: Debug 
  debug: 
    msg: "hostvars: {{ hostvars }}"

- name: Debug groups
  debug:
    msg: "Groups:   {{ groups }}"
 
- name: Debug group consulcluster.
  debug:
    msg: "Consulcluster group: {{ groups['consul-cluster'] }}"

- name: Debug service vars.
  debug:
    msg: "service vars: {{ consul_version }}, {{ consul_is_ui }}, {{ consul_install_consul_cli }}"

- name: Group vars.
  debug:
    msg: "Consulcluster group: {{ groups['consul-cluster'] }}"

- name: Group vars. ip addr.
  debug:
    msg: "Consul cluster ip addr {{ hostvars[groups['consul-cluster'][0]]['ipaddrs'] }}"


- name: group vars.
  debug:
    msg: "Group variables: {{ ipaddrs }}"

       
